config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new]
  resources :users, only: [:show, :create, :new]
  resource :session, only: [:create, :new, :destroy]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, :color, :sex, :name, presence: true
  validate :valid_sex?
  validates :owner, presence: true

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    primary_key: :id,
    foreign_key: :cat_id
  )

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  def age
    time_now = Time.now.to_date

    age = (time_now - birth_date).to_i / 365
  end

  private

  def valid_sex?
    if sex.length > 1
      errors[:valid_sex] << "Sex has to be 1 character long"
    elsif !["M", "F"].include?(sex)
      errors[:valid_sex] << "Sex must be M or F"
    end
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  validate :approved_overlapping_requests

  belongs_to(
    :cat,
    class_name: "Cat",
    primary_key: :id,
    foreign_key: :cat_id
  )

  private

  def overlapping_requests
    overlaps = cat.rental_requests
      .where("NOT (end_date < ? OR start_date > ?)", self.start_date, self.end_date)
  end

  def approved_overlapping_requests
    approved_overlaps = overlapping_requests
      .select{ |request| request.status == "APPROVED" }

    unless approved_overlaps.empty?
      status = "DENIED"
      errors[:valid_request] << "You can't make overlapping requests"
    end
  end

    # else
    #   deny_overlapping_approved_requests(overlaps)

  #     if request.status == "APPROVED"
  #       if !(request.end_date < self.start_date ||
  #            request.start_date > self.end_date)
  #         errors[:valid_request] << "Request overlaps with an existing request"
  #       end
  #     end
  #   end
  # end
  #
  # def deny_overlapping_approved_requests(unapproved_overlaps)
  #   unapproved_overlaps.each do |request|
  #     request.update('status = ?', "DENIED")
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, :password_digest, :session_token, presence:true
  after_initialize :ensure_token_created!
  # after_initialize do |user|
  #   self.session_token ||= SecureRandom::urlsafe_base64(16)
  # end

  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id
  )

  def self.find_by_credentials(username, password)
    user = User.find_by_user_name(username)
    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

  def password=(password)
    @password = BCrypt::Password.create(password)
    self.password_digest = @password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private
  def ensure_token_created!
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def require_sign_in
  end

  def sign_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def sign_out(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/cat_rental_request_controller.rb
class CatRentalRequestRentalRequestController < AppliCatRentalRequestionController
  # def index
  #   @CatRentalRequests = CatRentalRequest.all
  #   render :index
  # end
  #
  # def show
  #   @CatRentalRequest = CatRentalRequest.find(params[:id])
  #   render :show
  # end
  #
  # def edit
  #   @CatRentalRequest = CatRentalRequest.find(params[:id])
  #   render :edit
  # end

  def new
    @CatRentalRequest = CatRentalRequest.new
    render :new
  end

  # def create
  #   @CatRentalRequest = CatRentalRequest.new(CatRentalRequests_params)
  #
  #   if @CatRentalRequest.save
  #     redirect_to CatRentalRequest_url(@CatRentalRequest)
  #   else
  #     render json: @CatRentalRequest.errors.full_messages, status: :unprocessable_entity
  #   end
  # end
  #
  # def update
  #   @CatRentalRequest = CatRentalRequest.find(params[:id])
  #
  #   if @CatRentalRequest.update(CatRentalRequests_params)
  #     redirect_to CatRentalRequest_url(@CatRentalRequest)
  #   else
  #     render(json: @CatRentalRequest.errors.full_messages, status: :unprocessable_entity)
  #   end
  # end

  private

  def CatRentalRequests_params
    params.require(:CatRentalRequest).permit(:cat_id, :start_date, :end_date, :status)
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
    @all_cats = Cat.all
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_requests_params)

    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat_id)
    else
      render json: @cat_rental_request.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def cat_rental_requests_params
    params.require(:cat_rental_requests).permit(:cat_id, :start_date, :end_date, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_cat_owner, only: [:edit, :update]

  def index
    @all_cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cats_params)
    @cat.user_id = current_user.id

    if @cat.save

      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cats_params)
      redirect_to cat_url(@cat)
    else
      render(json: @cat.errors.full_messages, status: :unprocessable_entity)
    end
  end

  private

  def cats_params
    params.require(:cat).permit(:id, :birth_date, :color, :name, :sex, :description, :user_id)
  end

  def ensure_cat_owner
    current_cat = current_user.cats.where('id = ?', params[:id])
    redirect_to cats_url if current_cat.empty?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_signed_in, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:user_name], params[:user][:password])
    if user
      sign_in(user)
      redirect_to cats_url
    else
      render :new
    end
  end

  def destroy
    sign_out(current_user)
    redirect_to new_session_url
  end

  private

  def redirect_if_signed_in
    redirect_to cats_url if signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_signed_in

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    sign_in(@user)
    redirect_to cats_url
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :session_token, :password)
  end

  def redirect_if_signed_in
    redirect_to cats_url if signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Make a new rental request!</h1>

<form action="<%=cat_rental_requests_url%>" method="POST">

  <label for="rental_choice">Choose cat</label>

  <select name="cat_rental_requests[cat_id]" id="rental_choice">
    <% @all_cats.each do |cat| %>
      <option value="<%=cat.id%>">
        <%=cat.name%>
      </option>
    <% end %>
  </select>

  <br>
  <br>

  <label for="rental_start_date">Choose start date</label>
  <br>
  <input type="date" name="cat_rental_requests[start_date]" id="rental_start_date" value="<%= @cat_rental_request.start_date %>">

  <br>
  <br>

  <label for="rental_end_date">Choose end date</label>
  <br>
  <input type="date" name="cat_rental_requests[end_date]" id="rental_end_date" value="<%= @cat_rental_request.end_date %>">

  <br>
  <br>

  <input type="submit" value="SUBMIT">
</form>

app/views/cats/_form.html.erb
<html>


  <form action= "<%= @cat.persisted? ? cat_url(@cat.id) : cats_url %>" method="post">
    <input type="hidden" name="_method" value="<%= @cat.persisted? ? "PATCH" : "POST" %>" >

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="cat_name">Name</label><br>
    <input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">

    <br>
    <br>

    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "checked" if @cat.sex == "F"%> >
    <label for="cat_sex_female">Female</label>

    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= "checked" if @cat.sex == "M"%> >
    <label for="cat_sex_male">Male</label>

    <br>
    <br>

    <label for="cat_coat_color">Coat color</label>
    <br>
    <!-- dropdown -->
    <select name="cat[color]" id="cat_coat_color">
      <option></option>
      <option value="brown" <%= "selected" if @cat.color == "brown"%> >Brown</option>
      <option value="black" <%= "selected" if @cat.color == "black"%> >Black</option>
      <option value="blue" <%= "selected" if @cat.color == "blue"%> >Blue</option>
      <option value="tabby" <%= "selected" if @cat.color == "tabby"%> >Tabby</option>
      <option value="orange" <%= "selected" if @cat.color == "orange"%> >Orange</option>
      <option value="white" <%= "selected" if @cat.color == "white"%> >White</option>
    </select>

    <br>
    <br>

    <label for="cat_birth_date">Birthday</label>
    <br>
    <input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= @cat.birth_date %>">

    <br>
    <br>

    <label for="cat_description">Describe your cat here:</label>
    <br>
    <textarea name="cat[description]" id="cat_description" ><%=@cat.description%></textarea>

    <br>
    <br>

    <input type="submit" value="SUBMIT">
  </form>


</html>

app/views/cats/edit.html.erb
<html>
  <h1>Edit Details Regarding <%=@cat.name%> </h1>

  <%= render "form", cat: @cat %>
</html>

app/views/cats/index.html.erb
<html>
  <h1>Cat Rental Homepage</h1>
    <ul>
      <% @all_cats.each do |cat| %>
        <li>
          <a href= "<%= cat_url(cat.id) %>"> <%=cat.name%> </a>
        </li>
      <% end %>
    </ul>
</html>

app/views/cats/new.html.erb
<html>
  <h1>CREATE A NEW CAT WITHOUT THE 9 MONTH WAIT :) </h1>

  <%= render "form", cat: @cat %>
</html>

app/views/cats/show.html.erb
<html>
  <h1><%=@cat.name%></h1>
    <table style="width:50%">
      <% @cat.attributes.each do |attribute, val| %>
      <tr>
        <td>
          <%=attribute%>
        </td>
        <td>
          <%=val%>
        </td>
      </tr>
      <% end %>
    </table>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
</head>

<body>
  <% button_text = signed_in? ? "Sign Out" : "Sign In" %>
  <% method = signed_in? ? "DELETE" : "GET" %>
  <% action_url = signed_in? ? session_url : new_session_url %>

  <title>Rental99cats</title>
  <h1><%= current_user.user_name if signed_in? %> </h1>

  <form action= "<%= action_url %>" method = "POST" >
    <input type="hidden" name="_method" value="<%= method %>" >
    <input type="submit" value="<%= button_text %>">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </form>

  <%= yield %>

</body>

</html>

app/views/users/_form.html.erb
<% method = @user.persisted? ? "PATCH" : "POST" %>
<% submit_text = @user.persisted? ? "Edit user!" : "Create user!"%>

<form action= "<%= users_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_name">User name</label><br>
  <input type="text" name="user[user_name]" id="user_name" value="<%= @user.user_name %>">

  <br>
  <br>

  <label for="user_password">Password</label><br>
  <input type="password" name="user[password]" id="user_password">

  <br>
  <br>

  <input type="submit" value="<%= submit_text %>">

</form>

app/views/users/new.html.erb
<html>
  <h1>Register new user</h1>

  <%= render "form", user: @user %>
</html>